agent_name = "datadog-chatbot"
image = "hushdaily/datadog-chatbot:0.1"
image_credentials = "my-image-pull-secret"
secret_set = "datadog-chatbot-secrets"
enable_krisp = true

[scaling]
  min_agents = 0
