agent_name = "simple-chatbot-eu"
image = "hushdaily/simple-chatbot-eu:0.1"
image_credentials = "docker-creds"
secret_set = "simple-chatbot-eu-secrets"
region = "eu-central"
enable_krisp = true

[scaling]
  min_agents = 0
