agent_name = "datadog-chatbot"
image = "DOCKER_USERNAME/datadog-chatbot:0.1"
image_credentials = "DOCKER_CREDENTIALS"
secret_set = "datadog-chatbot-secrets"
enable_krisp = true

[scaling]
  min_agents = 0
