agent_name = "simple-chatbot-eu"
image = "DOCKER_USERNAME/simple-chatbot-eu:0.1"
image_credentials = "DOCKER_CREDENTIALS"
secret_set = "simple-chatbot-eu-secrets"
region = "eu-central"
enable_krisp = true

[scaling]
  min_agents = 0